# Generated by Django 3.2.4 on 2021-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeslots',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
