# Generated by Django 3.2.4 on 2021-06-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeslots_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeslots',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='employeeslots',
            name='status',
        ),
    ]
