# Generated by Django 3.2.4 on 2021-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeslots_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeslots',
            name='slots',
        ),
        migrations.AddField(
            model_name='employee',
            name='slots',
            field=models.CharField(choices=[(' 9:00 AM to 10:00 AM', ' 9:00 AM to 10:00 AM'), (' 10:00 AM to 11:00 AM', ' 10:00 AM to 11:00 AM'), (' 11:00 AM to 12:00 AM', ' 11:00 AM to 12:00 AM'), (' 12:00 PM to 01:00 PM', ' 12:00 PM to 01:00 PM'), (' 01:00 PM to 02:00 PM', ' 01:00 PM to 02:00 PM'), (' 02:00 PM to 03:00 PM', ' 02:00 PM to 03:00 PM'), (' 03:00 PM to 04:00 PM', ' 03:00 PM to 04:00 PM'), (' 04:00 PM to 05:00 PM', ' 04:00 PM to 05:00 PM'), (' 05:00 PM to 06:00 PM', ' 05:00 PM to 06:00 PM')], default='', max_length=50),
        ),
    ]
