# Generated by Django 3.2.4 on 2021-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210622_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slots',
        ),
        migrations.AddField(
            model_name='employeeslots',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
