# Generated by Django 3.2.4 on 2021-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210622_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeslots',
            name='meetingfromtime',
            field=models.CharField(blank=True, db_column='MeetingFromTime', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeslots',
            name='meetingtotime',
            field=models.CharField(blank=True, db_column='MeetingToTime', max_length=20, null=True),
        ),
    ]
